---
title: "Sobrevive"
format: pdf
editor: visual
---

```{r}
library(tidyverse)
library(googlesheets4)
library(ggthemes)
library(lubridate)
library(scales)
library(magick)
library(tinytex)

```

```{r}
biom <- read_sheet("1KkLM7bz-Az-etHUeENou-BjX4mDUfJCccwcCIo0k0CU", 2)

```

```{r}
sobrevive_ano <- biom %>%
  mutate(ano_desp = factor(year(data_desp))) %>%
  group_by(ano_desp) %>%
  summarize(sobrevive = median(sobrevive))

```

```{r}
sobrevive_ano %>%
  ggplot(aes(ano_desp, sobrevive)) +
  geom_point() +
  #geom_line() +
  geom_line(group = 1, color = "#8080c0", linewidth = 1) +
  expand_limits(y = 30) +
  labs(title = "Sobrevivência Anual (%)",
       x = "Ano",
       y = "Percentual",
       caption = "Azul Marinho Aquicultura") +
  geom_text(aes(label = sobrevive), vjust = 1.6, color = "#8080c0", size = 5.0) +
  theme_minimal() +
  theme(plot.caption = element_text(size = 9, color = "#8080c0"),
        axis.text.y = element_text(size = 12, color = "#000080"),
        axis.text.x = element_text(size = 12, color = "#000080"),
        axis.title.y = element_text(size = 15,
                                    color = "#000080",
                                    margin = margin(t = 0, r = 20, b = 0, l = 0)),
        axis.title.x = element_text(size = 15, color = "#000080"),
        plot.title = element_text(size = 20, color = "#000080"),
        axis.line.y = element_line(color = "#000080"),
        axis.line.x = element_line(color = "#000080"),
        panel.grid.major = element_blank())


```

```{r}
#logo <- image_read("G://My Drive//RWork//Projects//Azul Marinho//Cultivos//Images//azul_logo_transp.png")
#grid::grid.raster(logo, x = 0.92, y = 0.8, just = c('left', 'bottom'), width = unit(1.5, 'inches'))

```
