---
title: "Resultado 2023"
author: Mozart Marinho-Jr
format: 
  pdf:
    toc: true
    papersize: A4
editor: visual
execute: 
  echo: false
  warning: false
---

```{r}

#| libraries

library(tidyverse)
library(googlesheets4)
library(ggthemes)
library(lubridate)
library(ggrepel)
library(scales)
library(tinytex)
library(magick)

```

```{r}

#| Reading-data

biom <- read_sheet("1KkLM7bz-Az-etHUeENou-BjX4mDUfJCccwcCIo0k0CU", 2)

```

```{r}

#| Médias-2023

Means_2023 <- biom %>%
  group_by(viveiro) %>%
  mutate(ano_despesca = year(data_desp)) %>% 
  filter(ano_despesca == 2023) %>%  
  summarize(across(where(is.numeric), mean, na.rm = TRUE, .names = "mean_{col}"))

Means_2023

```

## Produção Anual

```{r}

biom_ano <- biom %>%
  mutate(ano_desp = year(data_desp)) %>% 
  filter(ano_desp != 2024) %>% #retirando o ano de 2024
  group_by(ano_desp) %>%
  summarize(biom_real = round(sum(biom_real), 2))
```

```{r}
biom_ano %>% 
  ggplot(aes(x = ano_desp, y = biom_real,)) +
  geom_bar(stat = "identity", width = 0.8, 
           show.legend = FALSE,
           fill = "#2e98fe") +
  labs(title = "Produção Anual",
       subtitle = "Azul Marinho Aquicultura",
       y = "Kg Produzidos",
       x = "Ano",
       caption = "Azul Marinho Aquicultura") +
  scale_y_continuous(
    labels = scales::label_number(big.mark = ".",
                                  decimal.mark = ","),
    expand = expansion(0),) + #faz as barras encostarem no eixo
  expand_limits(y = 65000) +
  scale_x_continuous(breaks = biom_ano$ano_desp) +
  theme_minimal() +
  theme(plot.caption = element_text(size = 9, color = "#8080c0"),
        axis.text.y = element_text(size = 15, color = "#000080"),
        axis.text.x = element_text(size = 15, color = "#000080"),
        axis.title.y = element_text(size = 20,
                                    color = "#000080",
                                    margin = margin(t = 0, r = 20, b = 0, l = 0)),
        axis.title.x = element_text(size = 20, color = "#000080"),
        plot.title = element_text(size = 25, color = "#000080"),
        plot.subtitle = element_text(size = 12, color = "#000080"),
        axis.line.y = element_line(color = "#000080"),
        axis.line.x = element_line(color = "#000080"),
        panel.grid.major = element_blank()) +
  geom_text(aes(label = format(biom_real, big.mark = ".", decimal.mark = ",")),
            vjust = -0.5, color = "#000080", size = 4.0) 

```

```{r}
logo <- image_read("G://My Drive//RWork//Projects//Azul Marinho//Cultivos//Images//azul_logo_transp.png")

grid::grid.raster(logo, x = 0.88, y = 0.85, just = c('left', 'bottom'), width = unit(0.9, 'inches'))

```

## Sobrevivência Anual por Viveiro

```{r}
sobrevive_viveiro <- biom %>%
  mutate(ano_desp = factor(year(data_desp)), viveiro = factor(viveiro)) %>%
  filter(ano_desp != 2024) %>%
  group_by(viveiro)
  #summarize(sobrevive = median(sobrevive))

```

```{r}
sobrevive_viveiro %>% 
  ggplot(aes(viveiro, sobrevive)) +
  geom_boxplot(fill = "#8080c0",
               col = "#000080",
               outlier.color = "#8080c0",
               outlier.size = 4,
               linetype = 1) +
  stat_summary(fun = mean, geom = "point", shape = 8, size = 3, color = "#c0c080", fill = "#c0c080") + 
  coord_flip() +
  labs(title = "Sobrevivência Anual por Viveiro (%)",
       subtitle = "2015 a 2023",
       x = "Viveiro",
       y = "Percentual",
       caption = "Azul Marinho Aquicultura") +
  theme_minimal() +
  theme(plot.caption = element_text(size = 9, 
                                    color = "#8080c0"),
        axis.text.y = element_text(size = 15, 
                                   color = "#000080"),
        axis.text.x = element_text(size = 15, 
                                   color = "#000080"),
        axis.title.y = element_text(size = 15,
                                    color = "#000080",
                                    margin = margin(t = 0, r = 20, b = 0, l = 0)),
        axis.title.x = element_text(size = 15, 
                                    color = "#000080"),
        plot.title = element_text(size = 20, 
                                  color = "#000080"),
        plot.subtitle = element_text(size = 15,
                                     color = "#000080" ),
        #axis.line.y = element_line(color = "#000080"),
        #axis.line.x = element_line(color = "#000080"),
        panel.grid.major = element_blank())
logo <- image_read("G://My Drive//RWork//Projects//Azul Marinho//Cultivos//Images//azul_logo_transp.png")
grid::grid.raster(logo, x = 0.8, y = 0.8, just = c('left', 'bottom'), width = unit(1.5, 'inches'))


```
